api:
  exchange: 'binance'
  api_key: 'TU_API_KEY'
  api_secret: 'TU_API_SECRET'

bot:
  symbol: 'BTC/USDT'
  timeframe: '1h'
  timeframe_seconds: 3600
  risk:
    max_position_size: 0.01
    take_profit: 0.01
    stop_loss: 0.005
