api:
  exchange: 'binance'
  api_key: 'TU_API_KEY'
  api_secret: 'TU_API_SECRET'

bot:
  symbol: 'BTC/USDT'
  timeframe: '1h'
  timeframe_seconds: 3600
  risk:
    max_position_size: 0.01
    take_profit: 0.01
    stop_loss: 0.005
  strategy:
    name: 'trend'
    short_window: 5
    long_window: 20
    grid_lower: 50000
    grid_upper: 60000
    grid_step: 500
    rsi_period: 14
    overbought: 70
    oversold: 30
    auto_trend_threshold: 0.01
